#!/bin/bash

PATH_EMMC="/dev/mmcblk0p2"
PATH_USB="/dev/sda2"
UUID_EMMC=`lsblk -o UUID -n /dev/mmcblk0p2`
UUID_USB=`lsblk -o UUID -n /dev/sda2`

DEV=`grep "^rootdev=" /mnt/emmc/armbianEnv.txt | sed 's:rootdev=::' | sed 's:UUID=::'`

case $DEV in
  $PATH_EMMC | $UUID_EMMC)
    echo "emmc"
    ;;

  $PATH_USB | $UUID_USB)
  echo "usb"
  ;;

  *)
  echo "unknown"
  ;;

esac
